# Generated by Django 5.2.4 on 2025-07-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите телеграм chat-id', max_length=50, null=True, verbose_name='Телеграм chat-id'),
        ),
    ]
