services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    working_dir: /code
    env_file:
      - ./.env
  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/code
      - celerybeat:/var/lib/celery
    working_dir: /code
    env_file:
      - ./.env
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html


volumes:
  postgres_data:
  redis_data:
  static_volume:
  celerybeat: