# Generated by Django 5.2.4 on 2025-07-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveIntegerField(choices=[('1', 'Ежедневно'), ('2', 'Каждые 2 дня'), ('3', 'Каждые 3 дня'), ('4', 'Каждые 4 дня'), ('5', 'Каждые 5 дней'), ('6', 'Каждые 6 дней'), ('7', 'Еженедельно')], default='1', help_text='Выберите периодичность', verbose_name='Периодичность'),
        ),
    ]
